name: My first workflow

# my trigger
on:
- push

jobs:
  # name of may job
  my-first-job:
    #runner
    runs-on: ubuntu-latest

    #steps in this job
    steps:
    - name:  checkout code
      uses: actions/checkout@v3
      run: trivy fs -s HIGH,CRITICAL