name: My first workflow

# my trigger
on:
- push

job:
  # name of may job
  my-first-job
    #runner
    runs-on: ubuntu-latest

    #steps in this job
    steps:
    - name: echo the date
      run: echo "hello, Github Action $(date)"
    - name: echo the git branch
      run: echo "hello, Github branch is ${{github.ref_name}}, ${{github.repositoryUrl}}"